name: force-reboot-runner

on:
  workflow_dispatch:

jobs:
  reboot:
    runs-on: self-hosted
    steps:
      - name: Force reboot
        run: |
          echo "Rebooting in 2s..."
          sleep 2
          sudo -n reboot || reboot || shutdown -r now
